---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((corporate-harbor-registry))/((dockerhub-organization))/release-ci-image
    tag: ((release-image-tag))
inputs:
  - name: git-repo
  - name: toolsmith-env
run:
  path: git-repo/ci/scripts/acceptance-tests.sh
params:
  TOOLSMITH_ENV_INPUT: toolsmith-env
  DEFAULT_ORG: ((acceptance-test-default-org))
  DEFAULT_SPACE: ((acceptance-test-default-space))
  SKIP_SSL_VALIDATION: ((acceptance-test-skip-ssl-validation))
  ONLY_SHOW_STANDARD_STREAMS_ON_TEST_FAILURE: true
