---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((docker-hub-organization))/release-ci-image
    tag: ((release-image-tag))
inputs:
  - name: git-repo
outputs:
  - name: distribution-repository
caches:
  - path: maven
  - path: gradle
run:
  path: git-repo/ci/scripts/build-project.sh
params:
  ONLY_SHOW_STANDARD_STREAMS_ON_TEST_FAILURE: true
