---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((corporate-harbor-registry))/((dockerhub-organization))/app-broker-ci
    tag: ((ci-image-tag))
inputs:
  - name: git-repo
  - name: artifactory-repo
outputs:
  - name: version
params:
  ARTIFACTORY_SERVER: ((artifactory-server))
  ARTIFACTORY_USERNAME: ((artifactory-username))
  ARTIFACTORY_PASSWORD: ((artifactory-password))
  BINTRAY_SUBJECT: ((bintray-subject))
  BINTRAY_REPO: ((bintray-repo))
  BINTRAY_USERNAME: ((bintray-username))
  BINTRAY_API_KEY: ((bintray-api-key))
  BINTRAY_PACKAGE: ((bintray-package))
  BINTRAY_DISTRIBUTION_REPO: ((bintray-distribution-repo))
run:
  path: git-repo/ci/scripts/distribute.sh
