---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((corporate-harbor-registry))/((dockerhub-organization))/release-ci-image
    tag: ((release-image-tag))
inputs:
  - name: git-repo
  - name: artifactory-repo
params:
  BINTRAY_REPO: ((bintray-repo))
  BINTRAY_SUBJECT: ((bintray-subject))
  BINTRAY_USERNAME: ((bintray-username))
  BINTRAY_API_KEY: ((bintray-api-key))
  BINTRAY_PACKAGE: ((bintray-package))
  SONATYPE_USER_TOKEN: ((sonatype-user-token))
  SONATYPE_PASSWORD_TOKEN: ((sonatype-password-token))
run:
  path: git-repo/ci/scripts/sync-to-maven-central.sh
