---
aliases:
  - &slack-success-notification
    put: alert
    params:
      icon_emoji: ":concourse:"
      username: concourse
      channel: ((ab-slack-success-channel))
      text: "$BUILD_PIPELINE_NAME pipeline has succeeded with build <https://scs.ci.springapps.io/builds/$BUILD_ID|$BUILD_NAME>!"
  - &slack-failure-notification
    put: alert
    params:
      icon_emoji: ":animal-1252:"
      username: concourse
      channel: ((ab-slack-failure-channel))
      text: <!here> Build <https://scs.ci.springapps.io/builds/$BUILD_ID|$BUILD_NAME> of job $BUILD_JOB_NAME in the $BUILD_PIPELINE_NAME pipeline has failed!

jobs:
  - name: build-release-ci-images
    plan:
      - get: ci-images-git-repo
        trigger: true
      - put: release-ci-image
        params:
          build: ci-images-git-repo/ci/images/release-ci-image

  - name: build
    serial: true
    public: true
    plan:
      - get: git-repo
        trigger: true
      - task: build-project
        timeout: 1h30m
        file: git-repo/ci/tasks/build-project.yml
        vars:
          release-image-tag: ((release-image-tag))
      - put: artifactory-repo
        params: &artifactory-params
          repo: libs-snapshot-local
          folder: distribution-repository
          build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
          build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
          disable_checksum_uploads: true
          artifact_set:
            - include:
                - "/**/spring-cloud-app-broker-*-docs.zip"
              properties:
                "zip.type": "docs"
                "zip.deployed": "false"

  - name: run-acceptance-tests
    serial: true
    plan:
      - get: git-repo
        passed: [build]
        trigger: true
      - task: acceptance-tests
        file: git-repo/ci/tasks/acceptance-tests.yml
    on_success:
      *slack-success-notification
    on_failure:
      *slack-failure-notification

  - name: stage-milestone
    serial: true
    plan:
      - get: git-repo
        trigger: false
        passed: [run-acceptance-tests]
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        vars:
          release-type: M
          release-image-tag: ((release-image-tag))
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo-staging
        params:
          repository: stage-git-repo

  - name: stage-rc
    serial: true
    plan:
      - get: git-repo
        trigger: false
        passed: [run-acceptance-tests]
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        vars:
          release-type: RC
          release-image-tag: ((release-image-tag))
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo-staging
        params:
          repository: stage-git-repo

  - name: stage-release
    serial: true
    plan:
      - get: git-repo
        trigger: false
        passed: [run-acceptance-tests]
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        vars:
          release-type: RELEASE
          release-image-tag: ((release-image-tag))
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo-staging
        params:
          repository: stage-git-repo

  - name: promote-milestone
    serial: true
    plan:
      - get: git-repo
        trigger: false
      - get: artifactory-repo
        trigger: false
        passed: [stage-milestone]
        params:
          save_build_info: true
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        vars:
          release-type: M
          release-image-tag: ((release-image-tag))

  - name: promote-rc
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
          trigger: false
        - get: artifactory-repo
          trigger: false
          passed: [stage-rc]
          params:
            save_build_info: true
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        vars:
          release-type: RC
          release-image-tag: ((release-image-tag))

  - name: promote-release
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
          trigger: false
        - get: artifactory-repo
          trigger: false
          passed: [stage-release]
          params:
            save_build_info: true
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        vars:
          release-type: RELEASE
          release-image-tag: ((release-image-tag))

  - name: distribute-release
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
          trigger: false
        - get: artifactory-repo
          trigger: false
          passed: [promote-release]
          params:
            save_build_info: true
      - task: distribute
        file: git-repo/ci/tasks/distribute.yml
        vars:
          release-image-tag: ((release-image-tag))

  - name: sync-to-maven-central
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
          trigger: false
        - get: artifactory-repo
          trigger: false
          passed: [distribute-release]
          params:
            save_build_info: true
      - task: sync-to-maven-central
        file: git-repo/ci/tasks/sync-to-maven-central.yml
        vars:
          release-image-tag: ((release-image-tag))

resource_types:
  - name: artifactory-resource
    type: docker-image
    source:
      repository: springio/artifactory-resource
      tag: 0.0.12

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: git-repo
    type: git
    source:
      uri: ((github-repo))
      username: ((github-username))
      password: ((github-password))
      branch: ((branch))
      ignore_paths: ["ci/images/*"]
      fetch_tags: true

  - name: git-repo-staging
    type: git
    source:
      uri: ((github-repo))
      username: ((github-username))
      password: ((github-password))
      branch: ((github-username))/staging
      git_config:
        - name: user.name
          value: ((git-username))
        - name: user.email
          value: ((git-email))

  - name: ci-images-git-repo
    type: git
    source:
      uri: ((github-repo))
      branch: ((branch))
      paths: ["ci/images/*"]

  - name: release-ci-image
    type: docker-image
    source:
      repository: ((docker-hub-organization))/release-ci-image
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      tag: ((release-image-tag))

  - name: artifactory-repo
    type: artifactory-resource
    source:
      uri: ((artifactory-server))
      username: ((artifactory-username))
      password: ((artifactory-password))
      build_name: ((build-name))

  - name: alert
    type: slack-notification
    source:
      url: ((scs-slack-webhook))

groups:
  - name: "Main"
    jobs:
      - build
      - run-acceptance-tests
      - stage-milestone
      - stage-rc
      - stage-release
      - promote-milestone
      - promote-rc
      - promote-release
      - distribute-release
      - sync-to-maven-central
  - name: "CI Images"
    jobs:
      - build-release-ci-images
